# Generated by Django 2.2.6 on 2019-10-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191019_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Question')),
                ('var_ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Choice')),
            ],
        ),
    ]
